version: '3.8'
services:
  app:
    hostname: app
    container_name: app_server
    environment:
      - ASPNETCORE_URLS=https://+:8443;http://+:8080
      # - ASPNETCORE_HTTPS_PORT=8443 
      - ASPNETCORE_Kestrel__Certificates__Default__Password=q1w2e3r4
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx 
      - ASPNETCORE_ENVIRONMENT=Stage
    volumes:
      - $USERPROFILE/.aspnet/https:/https/
    links:
      - "postgresql-server:database"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
      - '8443:8443'
    depends_on: 
      - postgresql-server
  
  postgresql-server:
    hostname: postgresql-server
    container_name: postgresql_server
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    volumes:
      - './postgres/data:/var/lib/postgresql/data'
      - './postgres/init.sql:/docker-entrypoint-initdb.d/init.sql'
    env_file:
      - .env
volumes:
  psql:
    external: false