FROM nginx:latest

# COPY default.conf /etc/nginx/conf.d/default.conf
# COPY aspnetapp.crt /etc/nginx/ssl/aspnetapp.crt
# COPY aspnetapp.key /etc/nginx/ssl/aspnetapp.key
# COPY aspnetapp.pem /etc/nginx/ssl/aspnetapp.pem
# COPY ssl_passwords /var/run/nginx/ssl_passwords


CMD ["nginx", "-g", "daemon off;"]  